### ISSUE TITLE
Two tables not necessary on manage rooms tab

### ISSUE THREAD

**Issue by HemantaNeupane** [Hostel-Management-System-Group-1/HMS#11]
After looking at the table structure on manage rooms page recently pushed by Ameesha, It is seen that two same tables are getting created. Please fix that.

![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/fc67a520-e53b-41ae-9f91-718936587a7f)

**Comment by ameek-web** [comment]
I'm currently working on it.

**Comment by ameek-web** [comment]
I solve the issue.
