### ISSUE TITLE
User login background color 

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#18]
Difficulty with the current user login background color. We need to adjust it to enhance visibility and improve user experience.
![ac632081-4f8c-4e61-8c8e-8a935d85a9de](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/c4747117-91d7-4648-9150-a2377d369e3c)

**Comment by Slex0p11** [comment]
Issue Solved: The user login background color has been adjusted to enhance visibility and improve the user experience. Thank you for bringing this to our attention
![Screenshot 2024-05-13 211740](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/492383a5-f5b6-4f76-9d3a-78cfd9f075f3)
