### ISSUE TITLE
Small User login frame 

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#19]
The disproportionate size of the user login frame is causing usability issues. Make an appropriate Frame instead
![5d7a34f8-56a2-4d17-89c1-6221d8afc36c](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/a6e3a536-09ab-42a9-a691-8583e1d7d0a7)
.

**Comment by Slex0p11** [comment]
Issue Solved: The disproportionate size of the user login frame has been addressed and additionally  I have added a frame for a login and background too
![Screenshot 2024-05-13 211915](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/1daf0e7a-25a0-4723-869c-7c677baa43a0)
