### ISSUE TITLE
Error in room details

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#20]
There seems to be an error in the room details section. Investigate and resolve this issue promptly to ensure accurate information for our users.
![438f625c-34a8-4288-9002-f16226bd6299](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/01806f58-281c-4617-bb63-efbf54a751c7)

**Comment by Slex0p11** [comment]
Issue Solved !!The error in the room details section has been investigated and resolved promptly to ensure accurate information for our users. Thank you for raising the issue  
![Screenshot 2024-05-13 205658](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/69fa4873-695b-4d36-b975-e932f8e83fe5)
