### ISSUE TITLE
Missing noticeboard in User Dashboard

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#21]
The absence of the noticeboard feature in the user dashboard is causing inconvenience. please prioritize its addition to enhance user engagement and communication.
![93fe0b97-ebb8-4e81-bff2-0ea8d29d2052](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/5c853988-9f0d-4230-be7f-f00cf4b3dd04)

**Comment by Slex0p11** [comment]
Issue Solved: The noticeboard feature has been added to the user dashboard to enhance user engagement and communication. Thank you for bringing this to our attention, and please feel free to reach out if you have any further suggestions or concerns.
![Screenshot 2024-05-13 204602](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/0d69d77b-5a5c-49b2-ac36-d611b03e29d0)
