### ISSUE TITLE
Change Admin Noticeboard Text Color

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#22]
Change the text color in the Admin Noticeboard for better readability and aesthetic consistency.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/2de8eb9f-8f43-414e-a952-a3a61aeecb07)

**Comment by HemantaNeupane** [comment]
Thank you for your attention, that could obviously be better as color contrasts doesn't match. Now the issue is resolved.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/abd7b4a8-3d58-4606-8b5d-3693cf225149)
