### ISSUE TITLE
Admin Approval not clear to User

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#25]
Users find the admin approval process unclear. We need to clarify it for better user understanding
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/aae108b2-abf8-47c8-9e3c-6a3f94275afd)

**Comment by HemantaNeupane** [comment]
Dear Mr. Niroj Thapa,

I'm pleased to inform you that the issue regarding the unclear admin approval process has been successfully resolved.
The resolution includes a toast message that clarifies that current user is not approved by admin.
![WhatsApp Image 2024-05-13 at 21 47 34_563b7ddc](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/29014b6c-b4f6-4681-8b64-0d6299fff14f)
