### ISSUE TITLE
Manage room features Error

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#26]
Critical: Manage room features are Errror, impacting functionality. Immediate action required.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/462af4a0-e21e-4627-8ccd-d00259a90c1f)

**Comment by ameek-web** [comment]
![Screenshot 2024-05-14 101339](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769993/0e45316a-b906-4773-a229-f6f783766b03)

**Comment by ameek-web** [comment]
: Manage room features were missing, impacting functionality. This has been resolved promptly.



Manage room features were missing, impacting functionality. This has been resolved promptly

**Comment by ameek-web** [comment]
Manage room features were missing, impacting functionality. This has been resolved promptly
