### ISSUE TITLE
Change background color of Admin Profile

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#27]
Need to change the background color of the Admin Profile for improved aesthetics and readability.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/daa52170-5b68-489a-8d86-42b63e583c89)

**Comment by ameek-web** [comment]
![Screenshot 2024-05-14 100057](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769993/bc78db7f-a15d-4430-9bed-c58ee3a88da6)

**Comment by ameek-web** [comment]
I have changed the background color of the Admin Profile for improved aesthetics and readability.
