### ISSUE TITLE
Room availability information 

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#28]
Room availability information for users is missing. Urgent attention required to rectify this issue
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/753c81d3-3b3d-4537-be1b-10f50cec8814)

**Comment by SuvamPoudel** [comment]
The issue regarding missing room availability information for users has been successfully resolved. Thank you for your patience and understanding.
![image (1)](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119736209/48dca393-6a34-46a4-bf45-2cc8a1139b53)
