### ISSUE TITLE
Spelling incorrect in Manage Students

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#30]
Typo found in 'Manage Students' section. Let's correct it promptly for accuracy.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/6d32921d-1595-4a17-9235-10c0ac1fbe51)

**Comment by ameek-web** [comment]
![Screenshot 2024-05-14 101339](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769993/aeb4c38f-12ad-4ef0-a2cc-7333ac31fe25)

**Comment by ameek-web** [comment]
I have solved the typo in the 'Manage Students' section.
