### ISSUE TITLE
Admin: Delete Noticeboard Item Missing

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#31]
Please implement a feature that allows admins to delete noticeboard items. Make sure only admins can access this functionality.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/9d777f07-fdff-4ebb-ac0a-7de7a8457a23)

**Comment by HemantaNeupane** [comment]
Solved !!! 

A clear button is added alongside Add Notice button. This button clears the notice board for adding new notices.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/d7dddfb3-1f5e-44b9-8c48-8f0f2ad80924)
