### ISSUE TITLE
Admin: Access Detailed Information About Hostel Residents

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#32]
Please fix error so that it allows admins to access detailed information about hostel residents Ensure that this feature is only accessible to admins.

![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/f244dd22-40b1-4bb8-ab04-639c8e07362d)

**Comment by HemantaNeupane** [comment]
Fixed !! And the feature is only accessible to the admin.

![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119563887/eabfc38e-0db5-4444-b223-fc763dda4bff)
