### ISSUE TITLE
Hostel Resident: Update Personal Information in Profile is Missing

### ISSUE THREAD

**Issue by Nerojthapa** [Hostel-Management-System-Group-1/HMS#33]
Please implement a feature that allows hostel residents to update their personal information in their profile while clicking on update profile button.
![image](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119769802/fab6194e-9c76-41a4-9ff2-b95bf46cf874)

**Comment by Slex0p11** [comment]
Issue Solved: The feature allowing hostel residents to update their personal information via the 'Update Profile' button has been successfully implemented. Users can now edit and save their profile information securely with confirmation upon update.
![Screenshot 2024-05-16 120925](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/c2bde5d0-59f6-4239-b675-56766f61b3bd)
![Screenshot 2024-05-16 121149](https://github.com/Hostel-Management-System-Group-1/HMS/assets/119754178/6c1f0e20-482a-4efd-880d-b5169a67e50d)
